server:
  port: 8888
  servlet:
    session:
      timeout: 15m
      cookie:
        http-only: true # js script can not access cookie data
#        secure: true # can send cookie only by https connection

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .html # 模版后缀名 默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/
#  security:
#    user:
#      name: admin
#      password: 123
  security:
    login-type: JSON
  session:
    timeout: 15m